### ISSUE TITLE
sql_drop_table is run everytime restarting the mongo-connector - any reason for this?

### ISSUE THREAD

**Issue by xinming** [Maltcommunity/mongo-connector-postgresql#18]
Hi - 

First of all, I would like to say that this is an amazing project that we've been looking for for a long time. Thanks for putting in the hard work! 

Currently the behaviour we are seeing is that, if the mongo-connector is stop for certain reason, on next startup, it will drop all the data, recreate the table, and continue the replication from according to the oplog timestamp. I wonder why are the sql tables dropped and recreated every time we start the mongo-connector? If the db schema is already in sync with the mappings, should't we just continue the replication without removing the old data? 

looking from the code, this seems to be the intended behaviour. Am I misconfiguring anything? Or is this some feature you guys have not got around to implement? (ie, handling restarts)

Thank you!

**Comment by hlassiege** [comment]
Hi,
This is not the expected behaviour. It occurs only if the process don't find a file "oplog.timestamp".
In this case, the process assume he has to sync from scratch the table.
