### ISSUE TITLE
Support for timestamp with time zone

### ISSUE THREAD

**Issue by JulieRossi** [Maltcommunity/mongo-connector-postgresql#20]
Hello !

Would you consider supporting postgres type `TIMESTAMP WITH TIME ZONE` ?

If I understand correctly, a mapping can only specify `TIMESTAMP` type which corresponds to `TIMESTAMP WITHOUT TIME ZONE`.

**Comment by hlassiege** [comment]
Hi,
Actually you can specify what you want in "type".
This mapping is valid : 
```
"field" : {
"dest" : "something",
"type" : "TIMESTAMP WITHOUT TIME ZONE"
}
```

For your information, we are currently rewriting the whole process here : 
https://github.com/Maltcommunity/mongo-postgresql-streamer
